package com.modelos.hibernate;
// Generated 5 may. 2021 19:19:57 by Hibernate Tools 5.4.27.Final

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import com.conexion.ConexionBBDD;
 

/**
 * CitaHora generated by hbm2java
 */
@SuppressWarnings("serial")
public class CitaHora implements java.io.Serializable, ICargaDatos {

	private int id;
	private String hora;

	public CitaHora() {
		this.id = 0;
	}
	public CitaHora(int id) {
		this.id = 0;
	}

	public CitaHora(int id, String hora) {
		this.id = id;
		this.hora = hora;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}
	
	@Override
	public String toString() {
		return getHora().substring(0, getHora().length() -3);
	}

	@Override
	public boolean cargar() {
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM CitasHora Where ID = " + this.getId());
			if(rs.next() == false) return false;
			else{
				setHora(rs.getString("Hora")); 
			}
		} catch (SQLException e) { 
			e.printStackTrace();
			return false;
		} 
		return true;
	}

	@Override
	public ArrayList<CitaHora> getLista() {
		ArrayList<CitaHora> lista = new ArrayList<CitaHora>();
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM CitasHora");
			while(rs.next()) {
				CitaHora g = new CitaHora(rs.getInt("Id"), rs.getString("Hora"));
				lista.add(g); 
			}
		} catch (SQLException e) { 
			e.printStackTrace();
		} 
		return lista;
	}

	 

}
