package com.modelos.hibernate;
// Generated 5 may. 2021 19:19:57 by Hibernate Tools 5.4.27.Final

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
 

import com.conexion.ConexionBBDD;

/**
 * Diente generated by hbm2java
 */
@SuppressWarnings("serial")
public class Diente implements java.io.Serializable, ICargaDatos {

	private int id;
	private String codigo;
	private String cuadrante;
	private String nombre;
	private String tipoDenticion; 

	public Diente() {
		this.id = 0;
	}
	public Diente(int id) {
		this.id = id;
	}
	
	public Diente(int id, String codigo, String cuadrante, String nombre, String tipoDenticion) {
		this.id = id;
		this.codigo = codigo;
		this.cuadrante = cuadrante;
		this.nombre = nombre;
		this.tipoDenticion = tipoDenticion;
	}
 

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getCuadrante() {
		return this.cuadrante;
	}

	public void setCuadrante(String cuadrante) {
		this.cuadrante = cuadrante;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getTipoDenticion() {
		return tipoDenticion;
	}
	public void setTipoDenticion(String tipoDenticion) {
		this.tipoDenticion = tipoDenticion;
	}
	
	
	@Override
	public String toString() {
		return "Nº: " + getCodigo() + "-" + getCuadrante();
	}

	@Override
	public boolean cargar() {
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM Dientes where id = " + getId());
			if(rs.next() == false) return false;
			else { 
				setCodigo(rs.getString("Codigo"));
				setCuadrante(rs.getString("Cuadrante"));
				setNombre(rs.getString("Nombre"));
				setTipoDenticion(rs.getString("TipoDenticion")); 
			} 
		} catch (SQLException e) { 
			e.printStackTrace();
			return false;
		} 
		return true;
	}

	@Override
	public ArrayList<Diente> getLista() {
		ArrayList<Diente> lista = new ArrayList<Diente>();
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM Dientes");
			while(rs.next()) {
				Diente p = new Diente();
				p.setId(rs.getInt("Id"));
				p.setCodigo(rs.getString("Codigo"));
				p.setCuadrante(rs.getString("Cuadrante"));
				p.setNombre(rs.getString("Nombre")); 
				p.setTipoDenticion(rs.getString("TipoDenticion"));				
				lista.add(p); 
			}
		} catch (SQLException e) { 
			e.printStackTrace();
		} 
		return lista;
	}
 

}
