package com.modelos.hibernate;
// Generated 5 may. 2021 19:19:57 by Hibernate Tools 5.4.27.Final
 
/**
 * Direccion generated by hbm2java
 */
@SuppressWarnings("serial")
public class Direccion implements java.io.Serializable {

	private int id;
	private String direccion;
	private String poblacion;
	private String codigoPostal;
	private String provincia;
	private String pais; 

	public Direccion() {
		this.id = 0;
		this.direccion = "";
		this.poblacion = "";
		this.codigoPostal = "";
		this.provincia = "";
		this.pais = "";
	}

	public Direccion(int id, String direccion, String poblacion, String codigoPostal, String provincia, String pais) {
		this.id = id;
		this.direccion = direccion;
		this.poblacion = poblacion;
		this.codigoPostal = codigoPostal;
		this.provincia = provincia;
		this.pais = pais;
	}
 
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigopostal) {
		this.codigoPostal = codigopostal;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}
 
	@Override
	public String toString() {
		return getDireccion() + ", " + getCodigoPostal() + "," + getProvincia() + "," + getPais();
	}

}
