package com.modelos.hibernate;
// Generated 5 may. 2021 19:19:57 by Hibernate Tools 5.4.27.Final

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList; 

import com.conexion.ConexionBBDD;

/**
 * Genero generated by hbm2java
 */
@SuppressWarnings("serial")
public class Genero implements java.io.Serializable, ICargaDatos {

	private int id;
	private String codigo;
	private String nombre; 

	public Genero() {
		this.id = 0;
		this.nombre = "";
	}
	public Genero(int id) {
		this.id = id; 
	}

	public Genero(int id, String codigo, String nombre) {
		this.id = id;
		this.codigo = codigo;
		this.nombre = nombre;
	}
 

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	 

	@Override
	public String toString() {
		return getNombre();
	}

	@Override
	public boolean cargar() {
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM Generos where id = " + this.getId());
			if(rs.next() == false) return false;
			else { 
				this.setCodigo(rs.getString("Codigo"));
				this.setNombre(rs.getString("Nombre")); 
			}
		} catch (SQLException e) { 
			e.printStackTrace();
			return false;
		} 
		return true;
	}

	@Override
	public ArrayList<Genero> getLista() {
		ArrayList<Genero> lista = new ArrayList<Genero>();
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM Generos");
			while(rs.next()) {
				Genero g = new Genero(rs.getInt("Id"), rs.getString("Codigo"), rs.getString("Nombre"));
				lista.add(g); 
			}
		} catch (SQLException e) { 
			e.printStackTrace();
		} 
		return lista;
	}
 
}
