package com.modelos.hibernate;
// Generated 5 may. 2021 19:19:57 by Hibernate Tools 5.4.27.Final

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
 
import com.conexion.ConexionBBDD;

/**
 * GrupoSanguineo generated by hbm2java
 */
@SuppressWarnings("serial")
public class GrupoSanguineo implements java.io.Serializable, ICargaDatos {

	private int id;
	private String codigo;
	private String puederecibirde;
	private String puededonara; 

	public GrupoSanguineo() {
		this.id = 0;
		this.codigo = "";
	}
	public GrupoSanguineo(int id) {
		this.id = id;
	}

	public GrupoSanguineo(int id, String codigo, String puederecibirde, String puededonara) {
		this.id = id;
		this.codigo = codigo;
		this.puederecibirde = puederecibirde;
		this.puededonara = puededonara;
	}
 

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getPuedeRecibirDe() {
		return this.puederecibirde;
	}

	public void setPuedeRecibirDe(String puederecibirde) {
		this.puederecibirde = puederecibirde;
	}

	public String getPuedeDonarA() {
		return this.puededonara;
	}

	public void setPuedeDonarA(String puededonara) {
		this.puededonara = puededonara;
	}
  
	 

	@Override
	public String toString() {
		return getCodigo();
	}

	@Override
	public boolean cargar() {
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM GruposSanguineo where id = " + this.getId());
			if(rs.next() == false) return false;
			else { 
				setCodigo(rs.getString("codigo"));
				setPuedeDonarA(rs.getString("PuedeDonarA"));
				setPuedeRecibirDe(rs.getString( "PuedeRecibirDe")); 
			}
		} catch (SQLException e) { 
			e.printStackTrace();
			return false;
		} 
		return true;
	}

	@Override
	public ArrayList<GrupoSanguineo> getLista() {
		ArrayList<GrupoSanguineo> lista = new ArrayList<GrupoSanguineo>();
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM GruposSanguineo");
			while(rs.next()) {
				GrupoSanguineo g = new GrupoSanguineo();
				g.setId(rs.getInt("id")); 
				g.setCodigo(rs.getString("codigo"));
				g.setPuedeDonarA(rs.getString("PuedeDonarA"));
				g.setPuedeRecibirDe(rs.getString( "PuedeRecibirDe")); 
				lista.add(g); 
			}
		} catch (SQLException e) { 
			e.printStackTrace();
		} 
		return lista;
	}
	
}
