package com.modelos.hibernate;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import com.conexion.ConexionBBDD;

// Generated 5 may. 2021 19:19:57 by Hibernate Tools 5.4.27.Final

/**
 * HistorialClinicoDetalle_Documento generated by hbm2java
 */
@SuppressWarnings("serial")
public class HistorialClinicoDetalle_Documento implements java.io.Serializable  {

	private int id; 
	private String fichero;
	private HistorialClinicoDetalle historialClinicoDetalle;

	public HistorialClinicoDetalle_Documento() {
		this.id = 0;
	}
 
	public HistorialClinicoDetalle_Documento(int id) {
		this.id = id;
	}

	public HistorialClinicoDetalle_Documento(int id, String fichero) {
		this.id = id; 
		this.fichero = fichero;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFichero() {
		return this.fichero;
	}

	public void setFichero(String fichero) {
		this.fichero = fichero;
	}
  

	public ArrayList<HistorialClinicoDetalle_Documento> getLista(HistorialClinicoDetalle historialClinicoDetalle) {
		ArrayList<HistorialClinicoDetalle_Documento> lista = new ArrayList<HistorialClinicoDetalle_Documento>();
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM HistorialClinicoDetalle_Documentos WHERE ID_HistorialClinicoDetalle = " + historialClinicoDetalle.getId());
			while(rs.next()) {
				HistorialClinicoDetalle_Documento p = new HistorialClinicoDetalle_Documento();
				p.setHistorialClinicoDetalle(historialClinicoDetalle);
				p.setId(rs.getInt("Id")); 
				p.setFichero(rs.getString("Fichero"));
				lista.add(p); 
			}
		} catch (SQLException e) { 
			e.printStackTrace();
		} 
		return lista;
	}

	public HistorialClinicoDetalle getHistorialClinicoDetalle() {
		return historialClinicoDetalle;
	}

	public void setHistorialClinicoDetalle(HistorialClinicoDetalle historialClinicoDetalle) {
		this.historialClinicoDetalle = historialClinicoDetalle;
	}

}
