package com.modelos.hibernate;
// Generated 5 may. 2021 19:19:57 by Hibernate Tools 5.4.27.Final

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import com.conexion.ConexionBBDD;

/**
 * HistorialClinicoDetalle_Receta generated by hbm2java
 */
@SuppressWarnings("serial")
public class HistorialClinicoDetalle_Receta implements java.io.Serializable {

	private int id; 
	private Medicamento medicamento;
	private String indicaciones;
	private HistorialClinicoDetalle historialClinicoDetalle;

	public HistorialClinicoDetalle_Receta() {
		this.id = 0;
		this.medicamento = new Medicamento();
	}
	public HistorialClinicoDetalle_Receta(int id) {
		this.id = id;
	}

	public HistorialClinicoDetalle_Receta(int id, Medicamento medicamentos, String indicaciones) {
		this.id = id; 
		this.medicamento = medicamentos;
		this.indicaciones = indicaciones;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
 
	public Medicamento getMedicamento() {
		return this.medicamento;
	}

	public void setMedicamento(Medicamento medicamentos) {
		this.medicamento = medicamentos;
	}

	public String getIndicaciones() {
		return this.indicaciones;
	}

	public void setIndicaciones(String indicaciones) {
		this.indicaciones = indicaciones;
	}

	public HistorialClinicoDetalle getHistorialClinicoDetalle() {
		return historialClinicoDetalle;
	}
	public void setHistorialClinicoDetalle(HistorialClinicoDetalle historialClinicoDetalle) {
		this.historialClinicoDetalle = historialClinicoDetalle;
	}

	
	public ArrayList<HistorialClinicoDetalle_Receta>  getLista(HistorialClinicoDetalle historialClinicoDetalle) {
		ArrayList<HistorialClinicoDetalle_Receta> lista = new ArrayList<HistorialClinicoDetalle_Receta>();
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM HistorialClinicoDetalle_Recetas WHERE ID_HistorialClinicoDetalle = " + historialClinicoDetalle.getId());
			while(rs.next()) {
				HistorialClinicoDetalle_Receta p = new HistorialClinicoDetalle_Receta();
				p.setHistorialClinicoDetalle(historialClinicoDetalle);
				p.setId(rs.getInt("Id"));
				Medicamento medicamento = new Medicamento(rs.getInt("Id_Medicamento"));
				medicamento.cargar();
				p.setMedicamento(medicamento);
				p.setIndicaciones(rs.getString("Indicaciones"));
				lista.add(p); 
			}
		} catch (SQLException e) { 
			e.printStackTrace();
		} 
		return lista;
	} 
}
