package com.modelos.hibernate;
// Generated 5 may. 2021 19:19:57 by Hibernate Tools 5.4.27.Final
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date; 

import com.conexion.ConexionBBDD;
 
 
/**
 * HistorialClinicoDetalle generated by hbm2java
 */
@SuppressWarnings("serial")
public class HistorialClinicoDetalle implements java.io.Serializable, IOperable {

	private int id; 
	private Cita cita;
	private HistorialClinico historialClinico;
	private Date fecha;
	private String habitosAlimenticios;
	private String medicacionActual;
	private String tratamientosAnteriores;
	private String observaciones;
	private Boolean sangradoExcesivo;
	private Boolean problemaSanguineo;
	private Boolean vih;
	private Boolean embarazada;
	private Boolean pastillasAnticonceptivas;
	private Boolean dificultadAbrirBoca;
	private Boolean ruidoAbrirCerrarBoca;
	private Boolean muerdeUnhas;
	private Boolean fuma;
	private Boolean consumoAlimentosCitricos;
	private Double pesoKg;
	private Double alturaCm;
	private Double temperaturaGrados;
	private Integer frecuenciaCardiaca; 
	private ArrayList<HistorialClinicoDetalle_Receta> historialClinicoDetalle_Receta;
	private ArrayList<HistorialClinicoDetalle_Documento> historialClinicoDetalle_Documento;
	private ArrayList<HistorialClinicoDetalle_Tratamiento> historialClinicoDetalle_Tratamiento;

	public HistorialClinicoDetalle() {
		this.id = 0; 
		this.setCita(new Cita());
		this.fecha = new Date(); 
		this.setHistorialClinicoDetalle_Receta(new ArrayList<HistorialClinicoDetalle_Receta>());
		this.setHistorialClinicoDetalle_Documento(new ArrayList<HistorialClinicoDetalle_Documento>());
		this.setHistorialClinicoDetalle_Tratamiento(new ArrayList<HistorialClinicoDetalle_Tratamiento>());
	}
	public HistorialClinicoDetalle(int id) {
		this.id = id;
	}
 
	
	public HistorialClinicoDetalle(int id, Date fecha) {
		this.id = id; 
		this.fecha = fecha;
	}

	public HistorialClinicoDetalle(int id, Date fecha, String habitosalimenticios,
			String medicacionactual, String tratamientosanteriores, String observaciones, Boolean sangradoexcesivo,
			Boolean problemasanguineo, Boolean vih, Boolean embarazada, Boolean pastillasanticonceptivas,
			Boolean dificultadabrirboca, Boolean ruidoabrircerrarboca, Boolean muerdeunhas, Boolean fuma,
			Boolean consumoalimentoscitricos, Double pesokg, Double alturacm, Double temperaturagrados,
			Integer frecuenciacardiaca) {
		this.id = id; 
		this.fecha = fecha;
		this.habitosAlimenticios = habitosalimenticios;
		this.medicacionActual = medicacionactual;
		this.tratamientosAnteriores = tratamientosanteriores;
		this.observaciones = observaciones;
		this.sangradoExcesivo = sangradoexcesivo;
		this.problemaSanguineo = problemasanguineo;
		this.vih = vih;
		this.embarazada = embarazada;
		this.pastillasAnticonceptivas = pastillasanticonceptivas;
		this.dificultadAbrirBoca = dificultadabrirboca;
		this.ruidoAbrirCerrarBoca = ruidoabrircerrarboca;
		this.muerdeUnhas = muerdeunhas;
		this.fuma = fuma;
		this.consumoAlimentosCitricos = consumoalimentoscitricos;
		this.pesoKg = pesokg;
		this.alturaCm = alturacm;
		this.temperaturaGrados = temperaturagrados;
		this.frecuenciaCardiaca = frecuenciacardiaca; 
	}
 
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}
 

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHabitosAlimenticios() {
		return this.habitosAlimenticios;
	}

	public void setHabitosAlimenticios(String habitosalimenticios) {
		this.habitosAlimenticios = habitosalimenticios;
	}

	public String getMedicacionActual() {
		return this.medicacionActual;
	}

	public void setMedicacionActual(String medicacionactual) {
		this.medicacionActual = medicacionactual;
	}

	public String getTratamientosAnteriores() {
		return this.tratamientosAnteriores;
	}

	public void setTratamientosAnteriores(String tratamientosanteriores) {
		this.tratamientosAnteriores = tratamientosanteriores;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Boolean getSangradoExcesivo() {
		return this.sangradoExcesivo;
	}

	public void setSangradoExcesivo(Boolean sangradoexcesivo) {
		this.sangradoExcesivo = sangradoexcesivo;
	}

	public Boolean getProblemaSanguineo() {
		return this.problemaSanguineo;
	}

	public void setProblemaSanguineo(Boolean problemasanguineo) {
		this.problemaSanguineo = problemasanguineo;
	}

	public Boolean getVih() {
		return this.vih;
	}

	public void setVih(Boolean vih) {
		this.vih = vih;
	}

	public Boolean getEmbarazada() {
		return this.embarazada;
	}

	public void setEmbarazada(Boolean embarazada) {
		this.embarazada = embarazada;
	}

	public Boolean getPastillasAnticonceptivas() {
		return this.pastillasAnticonceptivas;
	}

	public void setPastillasAnticonceptivas(Boolean pastillasanticonceptivas) {
		this.pastillasAnticonceptivas = pastillasanticonceptivas;
	}

	public Boolean getDificultadAbrirBoca() {
		return this.dificultadAbrirBoca;
	}

	public void setDificultadAbrirBoca(Boolean dificultadabrirboca) {
		this.dificultadAbrirBoca = dificultadabrirboca;
	}

	public Boolean getRuidoAbrirCerrarBoca() {
		return this.ruidoAbrirCerrarBoca;
	}

	public void setRuidoAbrirCerrarBoca(Boolean ruidoabrircerrarboca) {
		this.ruidoAbrirCerrarBoca = ruidoabrircerrarboca;
	}

	public Boolean getMuerdeUnhas() {
		return this.muerdeUnhas;
	}

	public void setMuerdeUnhas(Boolean muerdeunhas) {
		this.muerdeUnhas = muerdeunhas;
	}

	public Boolean getFuma() {
		return this.fuma;
	}

	public void setFuma(Boolean fuma) {
		this.fuma = fuma;
	}

	public Boolean getConsumoAlimentosCitricos() {
		return this.consumoAlimentosCitricos;
	}

	public void setConsumoAlimentosCitricos(Boolean consumoalimentoscitricos) {
		this.consumoAlimentosCitricos = consumoalimentoscitricos;
	}

	public Double getPesoKg() {
		return this.pesoKg;
	}

	public void setPesoKg(Double pesokg) {
		this.pesoKg = pesokg;
	}

	public Double getAlturaCm() {
		return this.alturaCm;
	}

	public void setAlturaCm(Double alturacm) {
		this.alturaCm = alturacm;
	}

	public Double getTemperaturaGrados() {
		return this.temperaturaGrados;
	}

	public void setTemperaturaGrados(Double temperaturagrados) {
		this.temperaturaGrados = temperaturagrados;
	}

	public Integer getFrecuenciaCardiaca() {
		return this.frecuenciaCardiaca;
	}

	public void setFrecuenciaCardiaca(Integer frecuenciacardiaca) {
		this.frecuenciaCardiaca = frecuenciacardiaca;
	}

	public Cita getCita() {
		return cita;
	}
	public void setCita(Cita cita) {
		this.cita = cita;
	}
	public ArrayList<HistorialClinicoDetalle_Receta> getHistorialClinicoDetalle_Receta() {
		return historialClinicoDetalle_Receta;
	}
	public void setHistorialClinicoDetalle_Receta(ArrayList<HistorialClinicoDetalle_Receta> historialClinicoDetalleReceta) {
		this.historialClinicoDetalle_Receta = historialClinicoDetalleReceta;
	}
	public ArrayList<HistorialClinicoDetalle_Documento> getHistorialClinicoDetalle_Documento() {
		return historialClinicoDetalle_Documento;
	}
	public void setHistorialClinicoDetalle_Documento(ArrayList<HistorialClinicoDetalle_Documento> historialClinicoDetalleDocumento) {
		this.historialClinicoDetalle_Documento = historialClinicoDetalleDocumento;
	}
	public ArrayList<HistorialClinicoDetalle_Tratamiento> getHistorialClinicoDetalle_Tratamiento() {
		return historialClinicoDetalle_Tratamiento;
	}
	public void setHistorialClinicoDetalle_Tratamiento(ArrayList<HistorialClinicoDetalle_Tratamiento> odontograma) {
		this.historialClinicoDetalle_Tratamiento = odontograma;
	}
	public HistorialClinico getHistorialClinico() {
		return historialClinico;
	}
	public void setHistorialClinico(HistorialClinico historialClinico) {
		this.historialClinico = historialClinico;
	}
	
	private ArrayList<String> getListaId_Documentos(){
		ArrayList<String> lista = new ArrayList<String>();
		for(HistorialClinicoDetalle_Documento tra : this.getHistorialClinicoDetalle_Documento()) lista.add(String.valueOf(tra.getId())); 
		return lista;
	}
	private ArrayList<String> getListaId_Recetas(){
		ArrayList<String> lista = new ArrayList<String>();
		for(HistorialClinicoDetalle_Receta tra : this.getHistorialClinicoDetalle_Receta())  lista.add(String.valueOf(tra.getId())); 
		return lista;
	}
	private ArrayList<String> getListaId_Tratamientos(){
		ArrayList<String> lista = new ArrayList<String>();
		for(HistorialClinicoDetalle_Tratamiento tra : this.getHistorialClinicoDetalle_Tratamiento()) lista.add(String.valueOf(tra.getId())); 
		return lista;
	}
	
	public Factura getFactura() { 
		return new Factura().getFactura(this);
	}
	
	

	@Override
	public boolean cargar() {
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM HistorialClinicoDetalle where id = " + getId());
			if(rs.next() == false) return false;
			else { 
				Cita cita = new Cita(rs.getInt("Id_Cita"));
				cita.cargar();
				setId(rs.getInt("Id"));
				setCita(cita);
				setFecha(rs.getDate("Fecha"));
				setHabitosAlimenticios(rs.getString("HabitosAlimenticios"));
				setMedicacionActual(rs.getString("MedicacionActual"));
				setTratamientosAnteriores(rs.getString("TratamientosAnteriores"));
				setObservaciones(rs.getString("Observaciones"));
				setSangradoExcesivo(rs.getBoolean("SangradoExcesivo"));
				setProblemaSanguineo(rs.getBoolean("ProblemaSanguineo"));
				setVih(rs.getBoolean("VIH"));
				setEmbarazada(rs.getBoolean("Embarazada"));
				setPastillasAnticonceptivas(rs.getBoolean("PastillasAnticonceptivas"));
				setDificultadAbrirBoca(rs.getBoolean("DificultadAbrirBoca"));
				setRuidoAbrirCerrarBoca(rs.getBoolean("RuidoAbrirCerrarBoca"));
				setMuerdeUnhas(rs.getBoolean("MuerdeUnhas"));
				setFuma(rs.getBoolean("Fuma"));
				setConsumoAlimentosCitricos(rs.getBoolean("ConsumoAlimentosCitricos"));
				setPesoKg(rs.getDouble("PesoKg"));
				setAlturaCm(rs.getDouble("PesoKg"));
				setTemperaturaGrados(rs.getDouble("TemperaturaGrados"));
				setFrecuenciaCardiaca(rs.getInt("FrecuenciaCardiaca"));
				setHistorialClinicoDetalle_Receta(new HistorialClinicoDetalle_Receta().getLista(this));
				setHistorialClinicoDetalle_Tratamiento(new HistorialClinicoDetalle_Tratamiento().getLista(this));
				setHistorialClinicoDetalle_Documento(new HistorialClinicoDetalle_Documento().getLista(this));
				HistorialClinico historialClinico = new HistorialClinico(rs.getInt("Id_HistorialClinico"));
				historialClinico.cargar();
				this.setHistorialClinico(historialClinico); 
			} 
		} catch (SQLException e) { 
			e.printStackTrace();
			return false;
		} 
		return true;
	}
	 

	@Override
	public ArrayList<HistorialClinicoDetalle> getLista() {
		ArrayList<HistorialClinicoDetalle> lista = new ArrayList<HistorialClinicoDetalle>();
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM HistorialClinicoDetalle");
			while(rs.next()) {
				HistorialClinicoDetalle p = new HistorialClinicoDetalle();
				Cita cita = new Cita(rs.getInt("Id_Cita"));
				cita.cargar();
				p.setId(rs.getInt("Id"));
				p.setCita(cita);
				p.setFecha(rs.getDate("Fecha"));
				p.setHabitosAlimenticios(rs.getString("HabitosAlimenticios"));
				p.setMedicacionActual(rs.getString("MedicacionActual"));
				p.setTratamientosAnteriores(rs.getString("TratamientosAnteriores"));
				p.setObservaciones(rs.getString("Observaciones"));
				p.setSangradoExcesivo(rs.getBoolean("SangradoExcesivo"));
				p.setProblemaSanguineo(rs.getBoolean("ProblemaSanguineo"));
				p.setVih(rs.getBoolean("VIH"));
				p.setEmbarazada(rs.getBoolean("Embarazada"));
				p.setPastillasAnticonceptivas(rs.getBoolean("PastillasAnticonceptivas"));
				p.setDificultadAbrirBoca(rs.getBoolean("DificultadAbrirBoca"));
				p.setRuidoAbrirCerrarBoca(rs.getBoolean("RuidoAbrirCerrarBoca"));
				p.setMuerdeUnhas(rs.getBoolean("MuerdeUnhas"));
				p.setFuma(rs.getBoolean("Fuma"));
				p.setConsumoAlimentosCitricos(rs.getBoolean("ConsumoAlimentosCitricos"));
				p.setPesoKg(rs.getDouble("PesoKg"));
				p.setAlturaCm(rs.getDouble("PesoKg"));
				p.setTemperaturaGrados(rs.getDouble("TemperaturaGrados"));
				p.setFrecuenciaCardiaca(rs.getInt("FrecuenciaCardiaca"));
				p.setHistorialClinicoDetalle_Receta(new HistorialClinicoDetalle_Receta().getLista(p));
				p.setHistorialClinicoDetalle_Tratamiento(new HistorialClinicoDetalle_Tratamiento().getLista(p));
				p.setHistorialClinicoDetalle_Documento(new HistorialClinicoDetalle_Documento().getLista(p)); 
				lista.add(p);
			}
		} catch (SQLException e) { 
			e.printStackTrace();
		} 
		return lista;
	}
	
 
	public ArrayList<HistorialClinicoDetalle> getLista(HistorialClinico historialClinico) {
		ArrayList<HistorialClinicoDetalle> lista = new ArrayList<HistorialClinicoDetalle>();
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM HistorialClinicoDetalle Where Id_HistorialClinico = " + historialClinico.getId());
			while(rs.next()) {
				HistorialClinicoDetalle p = new HistorialClinicoDetalle();
				Cita cita = new Cita(rs.getInt("Id_Cita"));
				cita.cargar();
				p.setId(rs.getInt("Id"));
				p.setCita(cita);
				p.setFecha(rs.getDate("Fecha"));
				p.setHabitosAlimenticios(rs.getString("HabitosAlimenticios"));
				p.setMedicacionActual(rs.getString("MedicacionActual"));
				p.setTratamientosAnteriores(rs.getString("TratamientosAnteriores"));
				p.setObservaciones(rs.getString("Observaciones"));
				p.setSangradoExcesivo(rs.getBoolean("SangradoExcesivo"));
				p.setProblemaSanguineo(rs.getBoolean("ProblemaSanguineo"));
				p.setVih(rs.getBoolean("VIH"));
				p.setEmbarazada(rs.getBoolean("Embarazada"));
				p.setPastillasAnticonceptivas(rs.getBoolean("PastillasAnticonceptivas"));
				p.setDificultadAbrirBoca(rs.getBoolean("DificultadAbrirBoca"));
				p.setRuidoAbrirCerrarBoca(rs.getBoolean("RuidoAbrirCerrarBoca"));
				p.setMuerdeUnhas(rs.getBoolean("MuerdeUnhas"));
				p.setFuma(rs.getBoolean("Fuma"));
				p.setConsumoAlimentosCitricos(rs.getBoolean("ConsumoAlimentosCitricos"));
				p.setPesoKg(rs.getDouble("PesoKg"));
				p.setAlturaCm(rs.getDouble("PesoKg"));
				p.setTemperaturaGrados(rs.getDouble("TemperaturaGrados"));
				p.setFrecuenciaCardiaca(rs.getInt("FrecuenciaCardiaca"));
				p.setHistorialClinicoDetalle_Receta(new HistorialClinicoDetalle_Receta().getLista(p));
				p.setHistorialClinicoDetalle_Tratamiento(new HistorialClinicoDetalle_Tratamiento().getLista(p));
				p.setHistorialClinicoDetalle_Documento(new HistorialClinicoDetalle_Documento().getLista(p)); 
				lista.add(p);
			}
		} catch (SQLException e) { 
			e.printStackTrace();
		} 
		return lista;
	}
	

	@Override
	public boolean guardar() {
		//Guardamos o actualizamos el paciente
				//Si el Id del paciente es 0, significa que hay que guardar un registro nuevo del paciente
				//Si el Id del paciente no es 0, significa que debemos actualizar los datos del paciente
				String sql = ""; 
				
				sql+= "UPDATE HistorialClinico "
						+ "	SET EnfermedadesFamiliares = " +  (this.getHistorialClinico().getEnfermedadesFamiliares() == null? "null" : "'" + this.getHistorialClinico().getEnfermedadesFamiliares().trim() + "'") +","
						+ "		AntecedentesPatologicos = " +  (this.getHistorialClinico().getAntecedentesPatologicos() == null? "null" : "'" + this.getHistorialClinico().getAntecedentesPatologicos().trim() + "'") +","
						+ "		Alergias = "+   (this.getHistorialClinico().getAlergias() == null? "null" : "'" + this.getHistorialClinico().getAlergias().trim() + "'")  
						+ "	WHERE Id = " + this.getHistorialClinico().getId() + "; ";
				
				if(this.getId() == 0) {
					sql +=  "INSERT INTO HistorialClinicoDetalle(Id_HistorialClinico, Id_Cita, Fecha, HabitosAlimenticios, MedicacionActual, TratamientosAnteriores,"
							+ "								   		Observaciones, SangradoExcesivo, ProblemaSanguineo, VIH, Embarazada, PastillasAnticonceptivas,"
							+ "								   			DificultadAbrirBoca, RuidoAbrirCerrarBoca, MuerdeUnhas, Fuma, ConsumoAlimentosCitricos, PesoKg,"
							+ "								   				AlturaCm, TemperaturaGrados, FrecuenciaCardiaca)"
							+ " VALUES(" + this.getHistorialClinico().getId() + "," +
										+ this.getCita().getId() + "," +
										"'" + new SimpleDateFormat("dd/MM/yyyy").format(this.getFecha()) + "'," +
										(this.getHabitosAlimenticios() == null? "null" : "'" + getHabitosAlimenticios() + "'") + "," +
										(this.getMedicacionActual() == null? "null" : "'" + getMedicacionActual() + "'") + "," +
										(this.getTratamientosAnteriores() == null? "null" : "'" + getTratamientosAnteriores() + "'") + "," +
										(this.getObservaciones() == null? "null" : "'" + getObservaciones() + "'") + "," +
										"'" + this.getSangradoExcesivo().toString() + "'," +
										"'" + this.getProblemaSanguineo().toString() + "'," +
										"'" + this.getVih().toString() + "'," +
										"'" + this.getEmbarazada().toString() + "'," +
										"'" + this.getPastillasAnticonceptivas().toString() + "'," +
										"'" + this.getDificultadAbrirBoca().toString() + "'," +
										"'" + this.getRuidoAbrirCerrarBoca().toString() + "'," +
										"'" + this.getMuerdeUnhas().toString() + "'," +
										"'" + this.getFuma().toString() + "'," +
										"'" + this.getConsumoAlimentosCitricos().toString() + "'," +
										(this.getPesoKg() == null? "null" : "'" + getPesoKg() + "'")  + "," +
										(this.getAlturaCm() == null? "null" : "'" + getAlturaCm() + "'")  + "," +
										(this.getTemperaturaGrados() == null? "null" : "'" + getTemperaturaGrados() + "'") + "," +
										(this.getFrecuenciaCardiaca() == null? "null" : "'" + getFrecuenciaCardiaca() + "'")  + 
								");"; 
				}else {
					 sql += "UPDATE HistorialClinicoDetalle "
					 		+ " SET HabitosAlimenticios = " + (this.getHabitosAlimenticios() == null? "null" : "'" + getHabitosAlimenticios() + "'") + ","
					 			+ " MedicacionActual = " + (this.getMedicacionActual() == null? "null" : "'" + getMedicacionActual() + "'") + "," 
					 			+ " TratamientosAnteriores = " + (this.getTratamientosAnteriores() == null? "null" : "'" + getTratamientosAnteriores() + "'") + "," 
					 			+ " Observaciones = " + (this.getObservaciones() == null? "null" : "'" + getObservaciones() + "'") + "," 
					 			+ " SangradoExcesivo = '" + this.getSangradoExcesivo().toString() + "',"
					 			+ " ProblemaSanguineo = '" + this.getProblemaSanguineo().toString() + "',"
					 			+ " VIH = '" + this.getVih().toString() + "',"
					 			+ " Embarazada = '" + this.getEmbarazada().toString() + "',"
					 			+ " PastillasAnticonceptivas = '" + this.getPastillasAnticonceptivas().toString() + "',"
					 			+ " DificultadAbrirBoca = '" + this.getDificultadAbrirBoca().toString() + "',"
					 			+ " RuidoAbrirCerrarBoca = '" + this.getRuidoAbrirCerrarBoca().toString() + "',"
					 			+ " MuerdeUnhas = '" + this.getMuerdeUnhas().toString() + "',"
					 			+ " Fuma = '" + this.getFuma().toString() + "',"
					 			+ " ConsumoAlimentosCitricos = '" + this.getConsumoAlimentosCitricos().toString() + "',"
					 			+ " PesoKg = " + (this.getPesoKg() == null? "null" : "'" + getPesoKg() + "'")  + "," 
					 			+ " AlturaCm = " + (this.getAlturaCm() == null? "null" : "'" + getAlturaCm() + "'")  + "," 
					 			+ " TemperaturaGrados = " + (this.getTemperaturaGrados() == null? "null" : "'" + getTemperaturaGrados() + "'")  + "," 
					 			+ " FrecuenciaCardiaca = " + (this.getFrecuenciaCardiaca() == null? "null" : "'" + getFrecuenciaCardiaca() + "'")  
					 	+ " WHERE ID = " + this.getId() + ";";
					 
				} 
				
				
				//Borramos/Modificamos/Insertamos los registros
				//Borramos los datos que no están en la lista de Tratamientos
				sql+= "DELETE FROM HistorialClinicoDetalle_Tratamientos "
						+ " WHERE ID_HistorialClinicoDetalle = " + this.getId() + 
						(this.getListaId_Tratamientos().size() == 0? ";" : " AND ID NOT IN (" + String.join(",", this.getListaId_Tratamientos()) + ");"); 
				
				//Borramos los datos que no están en la lista de Recetas
				sql+= "DELETE FROM HistorialClinicoDetalle_Recetas "
						+ " WHERE ID_HistorialClinicoDetalle = " + this.getId() + 
						(this.getListaId_Recetas().size() == 0? ";" : " AND ID NOT IN (" + String.join(",", this.getListaId_Recetas()) + ");");
				
				//Borramos los datos que no están en la lista de Documentos
				sql+= "DELETE FROM HistorialClinicoDetalle_Documentos "
						+ " WHERE ID_HistorialClinicoDetalle = " + this.getId() + 
						(this.getListaId_Documentos().size() == 0? ";" : " AND ID NOT IN (" + String.join(",", this.getListaId_Documentos()) + ");");
				
				
				//Insertamos/Modificamos los datos
				//Recorremos los tratamientos 
				for(HistorialClinicoDetalle_Tratamiento tra : this.getHistorialClinicoDetalle_Tratamiento())
				{
					if(tra.getId() == 0) { 
							sql += "INSERT INTO HistorialClinicoDetalle_Tratamientos(Observaciones, Id_Diente, Id_HistorialClinicoDetalle, Id_Tratamiento) VALUES " +
									"("+ (tra.getObservaciones() == null? "null" : "'" + tra.getObservaciones() + "'") + "," + 
										tra.getDiente().getId() + "," +
										"(SELECT MAX(ID) FROM HistorialClinicoDetalle)," + 
										tra.getTratamiento().getId() +						
									");";
					}else sql+= "UPDATE HistorialClinicoDetalle_Tratamientos SET Observaciones = " + (tra.getObservaciones() == null? "null" : "'" + tra.getObservaciones() + "'")  + " WHERE ID = " + String.valueOf(tra.getId()) + ";";
				} 
				//Recorremos las recetas 
				for(HistorialClinicoDetalle_Receta tra : this.getHistorialClinicoDetalle_Receta())
				{
					if(tra.getId() == 0) { 
							sql += "INSERT INTO HistorialClinicoDetalle_Recetas(Indicaciones, Id_Medicamento, Id_HistorialClinicoDetalle) VALUES " +
									"("+ (tra.getIndicaciones() == null? "null" : "'" + tra.getIndicaciones() + "'") + "," + 
										tra.getMedicamento().getId() + "," +
										"(SELECT MAX(ID) FROM HistorialClinicoDetalle)" +
									");";
					}else sql+= "UPDATE HistorialClinicoDetalle_Recetas SET Indicaciones = " + (tra.getIndicaciones() == null? "null" : "'" + tra.getIndicaciones() + "'") + " WHERE ID = " + String.valueOf(tra.getId()) + ";"; 
				} 
				//Recorremos los ficheros 
				for(HistorialClinicoDetalle_Documento tra : this.getHistorialClinicoDetalle_Documento())
				{
					if(tra.getId() == 0){
							sql += "INSERT INTO HistorialClinicoDetalle_Documentos(Fichero, Id_HistorialClinicoDetalle) VALUES " +
									"("+ (tra.getFichero() == null? "null" : "'" + tra.getFichero() + "'") + "," + 
										"(SELECT MAX(ID) FROM HistorialClinicoDetalle)" +
									");";
					}else sql+= "UPDATE HistorialClinicoDetalle_Documentos SET Fichero = " + (tra.getFichero() == null? "null" : "'" + tra.getFichero() + "'") + " WHERE ID = " + String.valueOf(tra.getId()) + ";"; 
				}
			 
				
				

			return ConexionBBDD.setDatos(sql); 
	}

	@Override
	public boolean esEliminable() {
		//Comprobamos si ya se ha facturado alguno de sus tratamientos
		if(Integer.parseInt(ConexionBBDD.getDato(
				"SELECT count(*)"
				+ "	FROM HistorialClinicoDetalle HCD"
					+ "	INNER JOIN HistorialClinicoDetalle_Tratamientos HCDT on HCDT.Id_HistorialClinicoDetalle = HCD.ID"
					+ "	INNER JOIN FacturaDetalle FD on FD.ID_HistorialClinicoDetalle_Tratamiento = HCDT.ID"
				+ " WHERE HCD.ID = " + this.getId()).toString()) > 0) return false;
		return true;
	} 

	
	public boolean esModificable() {
		return esEliminable();
	}
	
	@Override
	public boolean borrar() {
		 String sql = 
				 "DELETE "
				+ "	FROM HistorialClinicoDetalle"
				+ "	WHERE ID = " + this.getId();
			 return ConexionBBDD.setDatos(sql); 
	}
	
	
	public HistorialClinicoDetalle cargar(Cita cita) {
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT * FROM HistorialClinicoDetalle where id_Cita = " + cita.getId()); 
			if(rs.next() == true) {
				setId(rs.getInt("ID"));
				this.cargar();
			} 
		this.setCita(cita);
		this.setHistorialClinico(cita.getPaciente().getHistorialClinico());
		} catch (SQLException e) { 
			e.printStackTrace();
			return this;
		} 
		return this;
	}
	public ArrayList<HistorialClinicoDetalle> getListaVisitasPendientesFacturar(Date fechaInicio, Date fechaFin) {
		ArrayList<HistorialClinicoDetalle> lista = new ArrayList<HistorialClinicoDetalle>();
		try {
			ResultSet rs = ConexionBBDD.getDatos("SELECT HCD.*"
												+ "	FROM HistorialClinicoDetalle HCD"
												+ "	WHERE NOT EXISTS (SELECT 1"
															+ "	FROM HistorialClinicoDetalle_Tratamientos HT"
																+ "	INNER JOIN FacturaDetalle FD ON FD.ID_HistorialClinicoDetalle_Tratamiento = HT.ID"
															+ "	WHERE HT.ID_HistorialClinicoDetalle = HCD.ID) ");
			while(rs.next()) {
				HistorialClinicoDetalle p = new HistorialClinicoDetalle();
				Cita cita = new Cita(rs.getInt("Id_Cita"));
				cita.cargar();
				p.setId(rs.getInt("Id"));
				p.setCita(cita);
				p.setFecha(rs.getDate("Fecha"));
				p.setHabitosAlimenticios(rs.getString("HabitosAlimenticios"));
				p.setMedicacionActual(rs.getString("MedicacionActual"));
				p.setTratamientosAnteriores(rs.getString("TratamientosAnteriores"));
				p.setObservaciones(rs.getString("Observaciones"));
				p.setSangradoExcesivo(rs.getBoolean("SangradoExcesivo"));
				p.setProblemaSanguineo(rs.getBoolean("ProblemaSanguineo"));
				p.setVih(rs.getBoolean("VIH"));
				p.setEmbarazada(rs.getBoolean("Embarazada"));
				p.setPastillasAnticonceptivas(rs.getBoolean("PastillasAnticonceptivas"));
				p.setDificultadAbrirBoca(rs.getBoolean("DificultadAbrirBoca"));
				p.setRuidoAbrirCerrarBoca(rs.getBoolean("RuidoAbrirCerrarBoca"));
				p.setMuerdeUnhas(rs.getBoolean("MuerdeUnhas"));
				p.setFuma(rs.getBoolean("Fuma"));
				p.setConsumoAlimentosCitricos(rs.getBoolean("ConsumoAlimentosCitricos"));
				p.setPesoKg(rs.getDouble("PesoKg"));
				p.setAlturaCm(rs.getDouble("PesoKg"));
				p.setTemperaturaGrados(rs.getDouble("TemperaturaGrados"));
				p.setFrecuenciaCardiaca(rs.getInt("FrecuenciaCardiaca"));
				p.setHistorialClinicoDetalle_Receta(new HistorialClinicoDetalle_Receta().getLista(p));
				p.setHistorialClinicoDetalle_Tratamiento(new HistorialClinicoDetalle_Tratamiento().getLista(p));
				p.setHistorialClinicoDetalle_Documento(new HistorialClinicoDetalle_Documento().getLista(p));
				lista.add(p);
			}
		} catch (SQLException e) { 
			e.printStackTrace();
		} 
		return lista;
	}
 

}
