package com.modelos.hibernate;
// Generated 5 may. 2021 19:19:57 by Hibernate Tools 5.4.27.Final
  
import java.time.LocalDate;
import java.util.Date; 

/**
 * Sujeto generated by hbm2java
 */
@SuppressWarnings("serial")
public class Sujeto implements java.io.Serializable {

	private int id;
	private Direccion direccion;
	private Date fechaCreacion;
	private Date fechaNacimiento;
	private String nombre;
	private String apellidos;
	private String nif;
	private String email;
	private String telefono;
	private String foto; 
	private Usuario usuario;

	public Sujeto() {
		this.id = 0; 
		this.direccion = new Direccion();
		this.fechaNacimiento = new Date();
		this.fechaCreacion = new Date();
		this.nombre = "";
		this.apellidos = "";
		this.nif = "";
		this.email = "";
		this.telefono = "";
		this.foto = "";  
		this.usuario = new Usuario(); 
	}

	public Sujeto(int id, Direccion direccion, String nombre, String apellidos, String nif) {
		this.id = id;
		this.direccion = direccion;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.nif = nif;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Direccion getDireccion() {
		return this.direccion;
	}

	public void setDireccion(Direccion direccion) {
		this.direccion = direccion;
	}

	public Date getFechacreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechacreacion) {
		this.fechaCreacion = fechacreacion;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String teléfono) {
		this.telefono = teléfono;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	} 

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	public String getNombreCompleto() {
		return (this.getNombre() == null? "" : this.getNombre()) + " " + (this.getApellidos() == null? "": this.getApellidos());
	}
	

	@SuppressWarnings("deprecation")
	public int getEdad() {
		return Math.abs(java.sql.Date.valueOf(LocalDate.now()).getYear() - getFechaNacimiento().getYear());		 
	}

	@Override
	public String toString() {
		return getNombre() + " " + getApellidos();
	}

 

}
